apiVersion: batch/v1
kind: CronJob
metadata:
  name: claims-ingestion-job
  namespace: claims-processing
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ingestion-runner
              image: claimsinsightcr2026.azurecr.io/claims-pipeline-runner:TAG_PLACEHOLDER
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: claims-pipeline-config
          restartPolicy: OnFailure